name: Build & Deploy Backend API
on: [push]
defaults:
  run:
    working-directory: api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pipenv'
      - name: Install dependencies
        run: make deps
      - name: Run linting & tests
        run: make test
      - name: Deploy backend via serverless
        run: |
          npx serverless plugin install -n serverless-python-requirements
          npx serverless deploy --verbose
          npx serverless info >> $GITHUB_STEP_SUMMARY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
