source 'https://rubygems.org'

ruby '3.3.0'

gem 'bootsnap', require: false
gem 'enumerable-statistics', '~> 2.0'
gem 'nokogiri', '~> 1.16'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.3', '>= 7.1.3.4'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot_rails'
  gem 'rspec-rails', '~> 6.1.0'
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'ruby-lsp'
end
