name: Backend API
on: [push]
defaults:
  run:
    working-directory: backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pipenv'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run Linting
        run: pipenv run black --check .
      - name: Run Test's
        run: pipenv run pytest
      - name: Deploy backend via serverless
        run: |
          npx serverless plugin install -n serverless-python-requirements
          npx serverless deploy --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
