name: Backend API
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pipenv'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run linting
        run: pipenv run black --check .
      - name: Run Test's
        run: pipenv run pytest
